Debian bug 690524
When sshd passwordauthenication is turned off (key access only)
then DenyHost does not detect the denied log entry. This means
we are not blocking the remote host when multiple attempts are
made to access the local service. We should try to
detect bad connections to key-only systems.

In cases where DenyHosts cannot write to disk, it should not crash.

Consider support for IPv6

Create new sync server.

Update code to be compatible with Python version 3. Hopefully
we can maintain compatibility with Python version 2.7 and perhaps
other older verisons.

